package Model;

import java.util.Map;

import static java.util.Map.entry;

public class EmuLookupTables {
    public final static Map<String, String> new_licensees = Map.<String, String>ofEntries(
            entry("0", "none"),
            entry("1", "nintendo"),
            entry("8", "capcom"),
            entry("13", "electronic arts"),
            entry("18", "hudsonsoft"),
            entry("19", "b-ai"),
            entry("20", "kss"),
            entry("22", "pow"),
            entry("24", "pcm complete"),
            entry("25", "san-x"),
            entry("28", "kemco japan"),
            entry("29", "seta"),
            entry("30", "viacom"),
            entry("31", "nintendo"),
            entry("32", "bandia"),
            entry("33", "ocean/acclaim"),
            entry("34", "konami"),
            entry("35", "hector"),
            entry("37", "taito"),
            entry("38", "hudson"),
            entry("39", "banpresto"),
            entry("41", "ubi soft"),
            entry("42", "atlus"),
            entry("44", "malibu"),
            entry("46", "angel"),
            entry("47", "pullet-proof"),
            entry("49", "irem"),
            entry("50", "absolute"),
            entry("51", "acclaim"),
            entry("52", "activision"),
            entry("53", "american sammy"),
            entry("54", "konami"),
            entry("55", "hi tech entertainment"),
            entry("56", "ljn"),
            entry("57", "matchbox"),
            entry("58", "mattel"),
            entry("59", "milton bradley"),
            entry("60", "titus"),
            entry("61", "virgin"),
            entry("64", "lucasarts"),
            entry("67", "ocean"),
            entry("69", "electronic arts"),
            entry("70", "infogrames"),
            entry("71", "interplay"),
            entry("72", "broderbund"),
            entry("73", "sculptured"),
            entry("75", "sci"),
            entry("78", "t*hq"),
            entry("79", "accolade"),
            entry("80", "misawa"),
            entry("83", "lozc"),
            entry("86", "tokuma shoten i*"),
            entry("87", "tsukuda ori*"),
            entry("91", "chun soft"),
            entry("92", "video system"),
            entry("93", "ocean/acclaim"),
            entry("95", "varie"),
            entry("96", "yonezawa/s'pal"),
            entry("97", "kaneko"),
            entry("99", "pack in soft ")
    );
    public final static Map<String, String> old_licensees = Map.<String, String>ofEntries(
            entry("0x00", "none"),
            entry("0x01", "nintendo"),
            entry("0x08", "capcom"),
            entry("0x09", "hot-b"),
            entry("0x0A", "jaleco"),
            entry("0x0B", "coconuts"),
            entry("0x0C", "elite systems"),
            entry("0x13", "electronic arts"),
            entry("0x18", "hudsonsoft"),
            entry("0x19", "itc entertainment"),
            entry("0x1A", "yanoman"),
            entry("0x1D", "clary"),
            entry("0x1F", "virgin"),
            entry("0x24", "pcm complete"),
            entry("0x25", "san-x"),
            entry("0x28", "kotobuki systems"),
            entry("0x29", "seta"),
            entry("0x30", "infogrames"),
            entry("0x31", "nintendo"),
            entry("0x32", "bandai"),
            entry("0x34", "konami"),
            entry("0x35", "hector"),
            entry("0x38", "capcom"),
            entry("0x39", "banpresto"),
            entry("0x3C", "*entertainment i"),
            entry("0x3E", "gremlin"),
            entry("0x41", "ubi soft"),
            entry("0x42", "atlus"),
            entry("0x44", "malibu"),
            entry("0x46", "angel"),
            entry("0x47", "spectrum holoby"),
            entry("0x49", "irem"),
            entry("0x4A", "virgin"),
            entry("0x4D", "malibu"),
            entry("0x4F", "u.s. gold"),
            entry("0x50", "absolute"),
            entry("0x51", "acclaim"),
            entry("0x52", "activision"),
            entry("0x53", "american sammy"),
            entry("0x54", "gametek"),
            entry("0x55", "park place"),
            entry("0x56", "ljn"),
            entry("0x57", "matchbox"),
            entry("0x59", "milton bradley"),
            entry("0x5A", "mindscape"),
            entry("0x5B", "romstar"),
            entry("0x5C", "naxat soft"),
            entry("0x5D", "tradewest"),
            entry("0x60", "titus"),
            entry("0x61", "virgin"),
            entry("0x67", "ocean"),
            entry("0x69", "electronic arts"),
            entry("0x6E", "elite systems"),
            entry("0x6F", "electro brain"),
            entry("0x70", "infogrames"),
            entry("0x71", "interplay"),
            entry("0x72", "broderbund"),
            entry("0x73", "sculptered soft"),
            entry("0x75", "the sales curve"),
            entry("0x78", "t*hq"),
            entry("0x79", "accolade"),
            entry("0x7A", "triffix entertainment"),
            entry("0x7C", "microprose"),
            entry("0x7F", "kemco"),
            entry("0x80", "misawa entertainment"),
            entry("0x83", "lozc"),
            entry("0x86", "*tokuma shoten i"),
            entry("0x8B", "bullet-proof software"),
            entry("0x8C", "vic tokai"),
            entry("0x8E", "ape"),
            entry("0x8F", "i'max"),
            entry("0x91", "chun soft"),
            entry("0x92", "video system"),
            entry("0x93", "tsuburava"),
            entry("0x95", "varie"),
            entry("0x96", "yonezawa/s'pal"),
            entry("0x97", "kaneko"),
            entry("0x99", "arc"),
            entry("0x9A", "nihon bussan"),
            entry("0x9B", "tecmo"),
            entry("0x9C", "imagineer"),
            entry("0x9D", "banpresto"),
            entry("0x9F", "nova"),
            entry("0xA1", "hori electric"),
            entry("0xA2", "bandai"),
            entry("0xA4", "konami"),
            entry("0xA6", "kawada"),
            entry("0xA7", "takara"),
            entry("0xA9", "technos japan"),
            entry("0xAA", "broderbund"),
            entry("0xAC", "toei animation"),
            entry("0xAD", "toho"),
            entry("0xAF", "namco"),
            entry("0xB0", "acclaim"),
            entry("0xB1", "ascii or nexoft"),
            entry("0xB2", "bandai"),
            entry("0xB4", "enix"),
            entry("0xB6", "hal"),
            entry("0xB7", "snk"),
            entry("0xB9", "pony canyon"),
            entry("0xBA", "*culture brain o"),
            entry("0xBB", "sunsoft"),
            entry("0xBD", "sony imagesoft"),
            entry("0xBF", "sammy"),
            entry("0xC0", "taito"),
            entry("0xC2", "kemco"),
            entry("0xC3", "squaresoft"),
            entry("0xC4", "*tokuma shoten i"),
            entry("0xC5", "data east"),
            entry("0xC6", "tonkin house"),
            entry("0xC8", "koei"),
            entry("0xC9", "ufl"),
            entry("0xCA", "ultra"),
            entry("0xCB", "vap"),
            entry("0xCC", "use"),
            entry("0xCD", "meldac"),
            entry("0xCE", "*pony canyon or"),
            entry("0xCF", "angel"),
            entry("0xD0", "taito"),
            entry("0xD1", "sofel"),
            entry("0xD2", "quest"),
            entry("0xD3", "sigma enterprises"),
            entry("0xD4", "ask kodansha"),
            entry("0xD6", "naxat soft"),
            entry("0xD7", "copya systems"),
            entry("0xD9", "banpresto"),
            entry("0xDA", "tomy"),
            entry("0xDB", "ljn"),
            entry("0xDD", "ncs"),
            entry("0xDE", "human"),
            entry("0xDF", "altron"),
            entry("0xE0", "jaleco"),
            entry("0xE1", "towachiki"),
            entry("0xE2", "uutaka"),
            entry("0xE3", "varie"),
            entry("0xE5", "epoch"),
            entry("0xE7", "athena"),
            entry("0xE8", "asmik"),
            entry("0xE9", "natsume"),
            entry("0xEA", "king records"),
            entry("0xEB", "atlus"),
            entry("0xEC", "epic/sony records"),
            entry("0xEE", "igs"),
            entry("0xF0", "a wave"),
            entry("0xF3", "extreme entertainment"),
            entry("0xFF", "ljn")
    );
    public static Map<Integer, Integer> RAM_sizes = Map.ofEntries(
            entry(0x00, 0),
            entry(0x02, 8),
            entry(0x03, 32),
            entry(0x04, 128),
            entry(0x05, 64)
    );
    public static String[] cartridge_types = {
            "ROM ONLY",
            "MBC1",
            "MBC1+RAM",
            "MBC1+RAM+BATTERY",
            "0x04 ???",
            "MBC2",
            "MBC2+BATTERY",
            "0x07 ???",
            "ROM+RAM 1",
            "ROM+RAM+BATTERY 1",
            "0x0A ???",
            "MMM01",
            "MMM01+RAM",
            "MMM01+RAM+BATTERY",
            "0x0E ???",
            "MBC3+TIMER+BATTERY",
            "MBC3+TIMER+RAM+BATTERY 2",
            "MBC3",
            "MBC3+RAM 2",
            "MBC3+RAM+BATTERY 2",
            "0x14 ???",
            "0x15 ???",
            "0x16 ???",
            "0x17 ???",
            "0x18 ???",
            "MBC5",
            "MBC5+RAM",
            "MBC5+RAM+BATTERY",
            "MBC5+RUMBLE",
            "MBC5+RUMBLE+RAM",
            "MBC5+RUMBLE+RAM+BATTERY",
            "0x1F ???",
            "MBC6",
            "0x21 ???",
            "MBC7+SENSOR+RUMBLE+RAM+BATTERY"
    };
}
